# Generated by Django 2.2.17 on 2020-12-06 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='dest_code_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest_code', to='api.Ports'),
        ),
        migrations.AddField(
            model_name='prices',
            name='orig_code_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orig_code', to='api.Ports'),
        ),
    ]
