# Generated by Django 2.2.17 on 2020-12-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201206_0854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prices',
            name='dest_code',
        ),
        migrations.RemoveField(
            model_name='prices',
            name='orig_code',
        ),
    ]
