# Generated by Django 2.2.17 on 2020-12-06 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201206_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prices',
            old_name='dest_code_link',
            new_name='dest_code',
        ),
        migrations.RenameField(
            model_name='prices',
            old_name='orig_code_link',
            new_name='orig_code',
        ),
    ]
